# For toy data:

base:
  json_root: ~/src/voc2coco/sample/jsons/ # to save output all.json, train.json and val.json in
  imgs_root:  ~/src/voc2coco/JPEGImages # original imgs
  model_root: ~/src/voc2coco/sample/output/ # model output to save in

voc_to_coco:
  ann_root: ~/src/voc2coco/sample/Annotations
  labels: ["RBC", "WBC", "Platelets"]
  train_frac: 0.75
  
see_data:
  number_of_imgs: 5
  scale: 1.0

train_model:
  loss_rate: 0.02 # Pick a good loss rate
  max_iter: 300 # Max number of iterations
  eval_period: 100 # will do an evluation once every this many iters on cfg.DATASETS.TEST
  # TODO: param for SOLVER.STEPS
  # TODO: param for BATCH_SIZE_PER_IMAGE?

make_predictions:
  testing_thresh: 0.5 # set the testing threshold for this model