voc_to_coco:

  # For sample data:
  root: ~/src/voc2coco/sample/Annotations
  labels: ["RBC", "WBC", "Platelets"]
  output_dir: ~/src/voc2coco/sample/outputs/
  train_frac: 0.75

  # root:
  # labels:
  # output_dir:
  # train_frac: 0.75
  
see_data:
  imgs_root: ~/src/voc2coco/JPEGImages
  number_of_imgs: 5
  scale: 1.0