# # For toy data:

# base:
#   root:  ~/src/voc2coco/sample
#   imgs_root:  ~/src/voc2coco/JPEGImages # original imgs

# voc_to_coco:
#   ann_root: ~/src/voc2coco/sample/Annotations
#   labels: ["RBC", "WBC", "Platelets"]
#   train_frac: 0.75
  
# see_data:
#   number_of_imgs: 5
#   scale: 1.0

# train_model:
#   learning_rate: 0.02 # Pick a good learning rate
#   lr_decay_policy: [] # Each element in this list states the iteration no. at which the LR will decay by a factor of 10. If empty, the LR will not decay.
#   max_iter: 300 # Max number of iterations
#   eval_period: 100 # will do an evluation once every this many iters on cfg.DATASETS.TEST
#   checkpoint_period: 100 # will save the model .pth this many iterations; doesn't make sense for this val to be smaller than eval_period
#   # TODO: param for BATCH_SIZE_PER_IMAGE?

# test_model:
#   scale: 1.0 # TODO: lose this param?
#   do_show: false

# analyze_vids:
#   model_pth: 
#   score_cutoff: 0.8 # should be high for inference on actual videos
#   vids_root: 
#   framerate: 


# For my data:

base:
  # root: /home/hank-x299/tmp/test_run
  # imgs_root: /home/hank-x299/tmp/test_run/extracted_frames
  root:  ~/Dropbox/_mysci/models/detectron2/cashy
  imgs_root:  ~/Dropbox/_mysci/models/detectron2/cashy/extracted_frames

voc_to_coco:
  # ann_root: /home/hank-x299/tmp/test_run/labelled_imgs
  ann_root: ~/Dropbox/_mysci/models/detectron2/cashy/labels
  labels: ["dalotia", "ant"]
  train_frac: 0.8
  
see_data:
  number_of_imgs: 0 # if 0, will show all training data
  scale: 1.0

train_model:
  learning_rate: 0.02 # Pick a good learning rate
  lr_decay_policy: [1000, 5000] # Each element in this list states the iteration no. at which the LR will decay by a factor of 10. If empty, the LR will not decay.
  max_iter: 10000 # Max number of iterations
  eval_period: 500 # will do an evaluation once every this many iters on cfg.DATASETS.TEST
  checkpoint_period: 500 # will save the model .pth this many iterations; doesn't make sense for this val to be smaller than eval_period
  # TODO: param for BATCH_SIZE_PER_IMAGE?

test_model:
  scale: 1.0 # TODO: lose this param?
  do_show: false 
  # TODO: Make a note about how the predicted images are gonna look bad here
  # cuz im showing predictions after a SUPER low score cutoff. 

# TODO: Call this analyze_arena_vids and use it only for arena situations?
# TODO: Prevent overwriting files ... !!!!!!!!!!!!!!!!!!
analyze_vids:
  model_pth: ~/Dropbox/_mysci/models/detectron2/cashy/outputs/model_final.pth
  vid_ending: _undistorted.mp4
  expected_obj_nums: {dalotia: 1, ant: 1} # expected number of each label across the entirety of the video
  score_cutoff: 0.1 # should be high for inference on actual videos; get rid of this? make low for now just to grab high score
  vids_root: ~/tmp/test_run/
  # vids_root: /mnt/2TB/data_in/cashylinidae/tests # TODO: support single file conversions
  framerate: 30
  # TODO: rglob param? e.g. *_undistorted.mp4; implement this