# For toy data:

base:
  json_root: ~/src/voc2coco/sample/jsons/ # to save output all.json, train.json and val.json in
  imgs_root:  ~/src/voc2coco/JPEGImages # original imgs
  model_root: ~/src/voc2coco/sample/output/ # model output to save in

voc_to_coco:
  ann_root: ~/src/voc2coco/sample/Annotations
  labels: ["RBC", "WBC", "Platelets"]
  train_frac: 0.75
  
see_data:
  number_of_imgs: 5
  scale: 1.0

# TODO: Just mention this warning in the README: https://github.com/facebookresearch/detectron2/issues/196
train_model:
  learning_rate: 0.02 # Pick a good learning rate
  lr_decay_policy: [] # Each element in this list states the iteration no. at which the LR will decay by a factor of 10. If empty, the LR will not decay.
  max_iter: 300 # Max number of iterations
  eval_period: 100 # will do an evluation once every this many iters on cfg.DATASETS.TEST
  # TODO: param for BATCH_SIZE_PER_IMAGE?

make_predictions:
  testing_thresh: 0.5 # set the testing threshold for this model
  number_of_imgs: 5
  scale: 1.0
  do_show: false